module Game {
	interface Behaviour
	{
		string createPlayerAccount(in string FirstName, in string LastName, in short Age, in string Username,in string Password,in string IPAddress);
		string playerSignIn(in string Username,in string Password,in string IPAddress);
		string playerSignOut(in string Username,in string IPAddress);
		string getPlayerStatus(in string Username,in string Password,in string IPAddress);
		string suspendAccount(in string admin_username,in string admin_password,in string admin_ip_address,in string username);
		string transferAccount(in string username,in string password,in string old_IP_address,in string new_IP_address);
	};
	
};
